_BASE_: Base-ADE20K-SAM-Base-SemanticSegmentation.yaml
OUTPUT_DIR: 'output_vitb_5e-5_bb0.5_size1024_again'
MODEL:
  META_ARCHITECTURE: "MaskDINO"
#   DEVICE: "cpu"
  SEM_SEG_HEAD:
    NAME: "MaskDINOHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 2
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MaskDINOEncoder"
    DIM_FEEDFORWARD: 1024
    NUM_FEATURE_LEVELS: 3
    TOTAL_NUM_FEATURE_LEVELS: 3
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 0
  MaskDINO:
    TRANSFORMER_DECODER_NAME: "MaskDINODecoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 4.0 # 5 -> 4
    MASK_WEIGHT: 5.0 # 5 -> 4
    DICE_WEIGHT: 5.0 # 5 -> 4
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0 # 0.0 hj
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 9  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TWO_STAGE: False
    DN: "seg"
    DN_NUM: 100
    INITIALIZE_BOX_TYPE: "no"
    SEMANTIC_CE_LOSS: True
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
SOLVER:
  AMP:
    ENABLED: False
  BACKBONE_MULTIPLIER: 0.5
  BASE_LR: 5e-5 # 0.0001
  BIAS_LR_FACTOR: 0.1
  CHECKPOINT_PERIOD: 500

  IMS_PER_BATCH: 16
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  MAX_ITER: 40000 # 20000

  STEPS: (33750, 37500) # (8438,9375) # (4000, 4500)  (16875,18750)
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
  
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 512) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 1024
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (1024, 1024) # (512, 512)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 1024 # 512  # used in dataset mapper
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
TEST:
  EVAL_PERIOD: 500
  AUG:
    ENABLED: False
    MIN_SIZES: [1024, ] # [256, 384, 512, 640, 768, 896]
    MAX_SIZE: 1024 # 3584
    FLIP: True
